New design + picture
Proofme-id/sdk-example pull request #1
Opened 2023-06-27 08:56 UTC by 23Marvi

2023-06-27 10:57 UTC, Skyript requested changes

2023-06-27 10:57 UTC, Skyript commented on package.json
> +        "@proofme-id/sdk": "../Libraries/Proofme-SDK",
is this intentional, for the example?

2023-06-27 10:58 UTC, Skyript approved these changes

2023-06-27 11:46 UTC, ElkanRoelen requested changes

2023-06-27 11:46 UTC, ElkanRoelen commented on android/capacitor.settings.gradle
> +project(':proofme-id-sdk').projectDir = new File('../../Libraries/Proofme-SDK/./web/reader/android')
This will break the build!
You need to make sure that the sdk is installed by npm, and not linked to local filesystem.

2023-06-27 11:46 UTC, ElkanRoelen commented on angular.json
> +                                "input": "node_modules/@proofme-id/sdk/web/jp2",
Make sure to document this at https://docs.proofme.id/#/sdk_overview

2023-06-27 11:46 UTC, ElkanRoelen commented on capacitor.config.ts
>    appId: 'com.example.app',
can we update the app id?
Also for IOS?

2023-06-27 11:46 UTC, ElkanRoelen commented on src/app/app.component.ts
> +    readonly PROD_JWT = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOiJkaWQ6ZGlkdXg6MHg2NEJGNjA5N2E3MTJiZGIwOERENmZiOERDZjNmMTdCMTdiMERjOTRkIiwidmVyc2lvbiI6IjEuMC4wIiwic2NvcGUiOlsiTkZDIiwiTVJaIiwiT
unused JWT can be removed... Especially when it is prod!

2023-06-28 12:20 UTC, ElkanRoelen approved these changes

2023-06-28 12:20 UTC, merged