Feature/proof 611 all orientations scan UI
Proofme-id/sdk-example pull request #21
Opened 2023-11-15 14:56 UTC by DanielLeushuis

2023-11-21 11:52 UTC, 23Marvi requested changes

2023-11-21 11:52 UTC, 23Marvi commented on package.json
> +        "@proofme-id/sdk": "../Proofme-SDK",
Change off of local

2023-11-21 11:52 UTC, 23Marvi commented on src/app/app.component.scss
> +            margin-left: 4px;
Pls use rem() on both

2023-11-21 11:52 UTC, 23Marvi commented on src/app/app.component.ts
> +            let isDriverLicense = this.mrzCredentials.documentType === "D";
I don't see this being changed anywhere, change to const

2023-11-27 15:17 UTC, 23Marvi approved these changes

2023-11-27 15:24 UTC, Skyript approved these changes

2023-11-27 15:25 UTC, merged